%YAML 1.2
---
application:
  title: MONAI Deploy App Package - AI-READI Laterality Classifier
  version: 1.0
  inputFormats: ["file"]
  outputFormats: ["file"]

resources:
  cpu: 1
  gpu: 1
  memory: 2Gi
  gpuMemory: 2Gi
